"""一键 Nuitka + PyInstaller 打包脚本（先编译，再封装）

目标
- 先用 Nuitka 把你的 Camera.py 编译成 CPython 扩展模块（.pyd/.so），避免把源码 .py 打进包里
- 再用 PyInstaller 负责“分发封装”（图标、依赖、海康 DLL 等）

说明（非常关键）
- 扩展模块的“模块名”和“文件名”必须一致，不能随意改名；因此这里会临时复制 Camera.py 为 camera_core.py 来编译。
- PyInstaller 无法从已编译的扩展模块里自动分析 import 依赖，所以需要显式写 hidden-import / collect-all。
"""

import os
import shutil
import subprocess
import sys
from importlib.machinery import EXTENSION_SUFFIXES
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

# ---------- 你的项目文件 ----------
CAMERA_SRC = PROJECT_ROOT / "Camera.py"
ICON_FILE = PROJECT_ROOT / "Camera.ico"
WIN64_DIR = PROJECT_ROOT / "Win64_x64"

# ---------- Nuitka 输出 ----------
NUITKA_MODULE_NAME = "camera_core"  # 生成的扩展模块名
NUITKA_TEMP_PY = PROJECT_ROOT / f"{NUITKA_MODULE_NAME}.py"
NUITKA_OUT_DIR = PROJECT_ROOT / "build_nuitka"

# ---------- PyInstaller 输出 ----------
ENTRY_SCRIPT = PROJECT_ROOT / "Camera_entry.py"   # PyInstaller 入口
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"
SPEC_FILE = PROJECT_ROOT / "Camera.spec"

# 这些模块都在 Camera.py 里有 import（但 PyInstaller 现在看不到 Camera.py 了，所以要显式告诉它）
HIDDEN_IMPORTS = [
    # 业务依赖
    "onnxruntime",
    "cv2",
    "numpy",

    # PyQt5（保证 hook 能触发，打包 Qt 插件）
    "PyQt5",
    "PyQt5.QtCore",
    "PyQt5.QtGui",
    "PyQt5.QtWidgets",

    # 海康 SDK 的 Python 包装（Camera.py 里 try-import 这些）
    "MvCameraControl_class",
    "CameraParams_const",
    "CameraParams_header",
    "MvErrorDefine_const",
    "PixelType_header",
]

# 复制 metadata（你原脚本里就有，继续保留；多加了 PyQt5 以防某些环境缺元数据）
METADATA_PACKAGES = [
    "onnxruntime",
    "opencv-python",
    "numpy",
    "PyQt5",
]


def _rm(path: Path) -> None:
    if path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path, ignore_errors=True)


def clean_previous_artifacts() -> None:
    """删除上一次构建的产物，确保干净输出。"""
    for p in (DIST_DIR, BUILD_DIR, SPEC_FILE, NUITKA_OUT_DIR):
        _rm(p)

    # 清理上一次生成的入口/临时文件
    for p in (ENTRY_SCRIPT, NUITKA_TEMP_PY):
        if p.exists():
            p.unlink()

    # 清理根目录里可能残留的编译产物（camera_core*.pyd/.so 等）
    for item in PROJECT_ROOT.iterdir():
        if item.is_file() and item.name.startswith(NUITKA_MODULE_NAME) and any(
            item.name.endswith(suf) for suf in EXTENSION_SUFFIXES
        ):
            item.unlink()


def prepare_nuitka_source() -> None:
    """临时复制 Camera.py -> camera_core.py，让 Nuitka 用 camera_core 作为模块名编译。"""
    if not CAMERA_SRC.exists():
        raise FileNotFoundError(f"找不到 {CAMERA_SRC}")

    # 直接复制即可；Camera.py 只有在 __main__ 时才会 main()
    shutil.copy2(CAMERA_SRC, NUITKA_TEMP_PY)


def run_nuitka_compile() -> Path:
    """使用 Nuitka 把 camera_core.py 编译为扩展模块，并返回编译产物路径。"""
    NUITKA_OUT_DIR.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable,
        "-m",
        "nuitka",
        "--module",
        f"--output-dir={NUITKA_OUT_DIR}",
        "--no-pyi-file",               # 不生成 .pyi（可选）
        "--assume-yes-for-downloads",  # Nuitka 需要下载时自动同意（可选）
        str(NUITKA_TEMP_PY),
    ]

    subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

    # 在输出目录里找 camera_core 的扩展模块文件
    candidates = []
    for p in NUITKA_OUT_DIR.iterdir():
        if p.is_file() and p.name.startswith(NUITKA_MODULE_NAME) and any(
            p.name.endswith(suf) for suf in EXTENSION_SUFFIXES
        ):
            candidates.append(p)

    if not candidates:
        raise FileNotFoundError(
            f"未在 {NUITKA_OUT_DIR} 找到编译产物（{NUITKA_MODULE_NAME}*.pyd/.so）。"
        )

    # 若存在多个，按字典序取一个最可能的（通常是带 cp311-win_amd64 的那个）
    candidates.sort(key=lambda x: x.name)
    built_module = candidates[0]

    # 复制到项目根目录，确保 PyInstaller 能 import 到
    target = PROJECT_ROOT / built_module.name
    shutil.copy2(built_module, target)
    return target


def write_entry_script() -> None:
    """生成 PyInstaller 入口脚本：import 扩展模块并调用 main()."""
    content = """# Auto-generated by build script
import os, sys

base = getattr(sys, "_MEIPASS", os.path.dirname(__file__))

import camera_core

if __name__ == "__main__":
    camera_core.main()
"""
    ENTRY_SCRIPT.write_text(content, encoding="utf-8")


def run_pyinstaller() -> None:
    """调用 PyInstaller 进行打包。"""
    data_sep = ";" if os.name == "nt" else ":"
    add_data_arg = f"{ICON_FILE}{data_sep}."  # 将图标文件复制到 dist 根目录

    binaries = []
    if WIN64_DIR.exists():
        for item in WIN64_DIR.iterdir():
            if item.is_file():
                binaries.extend(["--add-binary", f"{item}{data_sep}Win64_x64"])

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--noconsole",
        "--name",
        "Camera",
        "--icon",
        str(ICON_FILE),
        "--add-data",
        add_data_arg,

        # 关键：确保 Qt / OpenCV 等 hook 资源被完整收集
        "--collect-all",
        "PyQt5",
        "--collect-all",
        "cv2",
    ]

    for hidden in HIDDEN_IMPORTS:
        cmd.extend(["--hidden-import", hidden])

    for meta_pkg in METADATA_PACKAGES:
        cmd.extend(["--copy-metadata", meta_pkg])

    cmd.extend([
        *binaries,
        str(ENTRY_SCRIPT),
    ])

    subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)


def remove_unwanted_files() -> None:
    """确保输出目录中不包含 config.json。"""
    if not DIST_DIR.exists():
        return

    for candidate in DIST_DIR.iterdir():
        if candidate.is_dir():
            cfg = candidate / "config.json"
            if cfg.exists():
                cfg.unlink()
        elif candidate.is_file() and candidate.name == "config.json":
            candidate.unlink()


def cleanup_temp_files() -> None:
    """构建完成后清理临时源码文件（可按需保留用于下次增量构建）。"""
    for p in (ENTRY_SCRIPT, NUITKA_TEMP_PY):
        if p.exists():
            p.unlink()


def main() -> None:
    clean_previous_artifacts()
    prepare_nuitka_source()

    built_ext = run_nuitka_compile()
    print(f"[OK] Nuitka built: {built_ext.name}")

    write_entry_script()
    run_pyinstaller()
    remove_unwanted_files()
    cleanup_temp_files()
    print("[OK] Done. Check dist/Camera/ ...")


if __name__ == "__main__":
    main()
